import { StyleSheet, Dimensions } from 'react-native';

const { width, height } = Dimensions.get('window');
const scale = size => (width / 428) * size;

export default StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#F0F0F0',
    },
    map: {
        flex: 1,
    },
    zoomControls: {
        position: 'absolute',
        bottom: scale(20),
        right: scale(20),
        backgroundColor: 'transparent',
    },
    iconContainer: {
        width: scale(50),
        height: scale(50),
        borderRadius: scale(10),
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: scale(16),
    },
    zoomButton: {
        backgroundColor: '#ffffff',
        marginBottom: scale(10),
        alignItems: 'center',
        justifyContent: 'center',
        padding: scale(10),
        borderRadius: scale(30),
        elevation: scale(5),
        shadowColor: '#000',
        shadowOffset: { width: 0, height: scale(4) },
        shadowOpacity: 0.1,
        shadowRadius: scale(5),
    },
    pennStateButton: {
        position: 'absolute',
        bottom: scale(10),
        right: scale(350),
        backgroundColor: '#ffffff',
        borderRadius: scale(30),
        elevation: scale(5),
        padding: scale(10),
    },
    currentLocationButton: {
        backgroundColor: '#ffffff',
        position: 'absolute',
        bottom: scale(125),
        right: scale(0),
        borderRadius: scale(30),
        padding: scale(10),
        elevation: scale(5),
    },
    pennStateIcon: {
        width: scale(30),
        height: scale(30),
    },
    emergencyItem: {
        borderColor: 'red',
        borderWidth: scale(2),
    },
    emergency: {
        color: 'red',
        fontWeight: 'bold',
    },
    searchContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    backgroundColor: 'white', 
    },
    searchInput: {
    flex: 1, 
    backgroundColor: '#f2f2f2',
    borderRadius: 10,
    padding: 15,
    marginRight: 10, 
    },
    filterButton: {
    backgroundColor: '#007bff',
    paddingVertical: 10,
    paddingHorizontal: 20,
    justifyContent: 'center',
    alignItems: 'center',
    },
    filterButtonText: {
    color: 'white',
    fontSize: 16,
    },
    eventItem: {
        backgroundColor: '#ffffff',
        borderRadius: scale(8),
        padding: scale(12),
        marginVertical: scale(6),
        marginHorizontal: scale(8),
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: scale(1) },
        shadowOpacity: 0.2,
        shadowRadius: scale(2),
        elevation: scale(2),
    },
    title: {
        fontSize: scale(16),
        fontWeight: 'bold',
        color: '#333',
        marginBottom: scale(4),
    },
    description: {
        fontSize: scale(12),
        color: '#999',
        lineHeight: scale(18),
    },
    buttonsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginLeft: 'auto',
    },
    button: {
        marginLeft: scale(8),
        width: scale(36),
        height: scale(36),
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: scale(18),
        backgroundColor: '#007bff',
    },
    buttonText: {
        color: '#fff',
        fontSize: scale(12),
        fontWeight: 'bold',
    },
    customMarker: {
        backgroundColor: 'white',
        padding: scale(5),
        borderRadius: scale(15),
        borderWidth: scale(1),
        borderColor: 'gray',
        alignItems: 'center',
        justifyContent: 'center',
    },
    markerText: {
        fontWeight: 'bold',
        color: 'black',
    },
    customCallout: {
        borderRadius: scale(5),
        padding: scale(10),
        backgroundColor: '#FFF',
        borderColor: '#DDD',
        borderWidth: scale(1),
        width: scale(250),
    },
    calloutTitle: {
        fontWeight: 'bold',
        marginBottom: scale(5),
    },
    calloutDescription: {
        color: '#666',
    },
    viewDetailsButton: {
        marginTop: scale(10),
        backgroundColor: "#007bff",
        padding: scale(10),
        borderRadius: scale(5),
    },
    viewDetailsButtonText: {
        color: "#ffffff",
        textAlign: "center",
    },
    customMarkerView: {
        backgroundColor: "#007bff",
        padding: scale(5),
        borderRadius: scale(10),
        borderWidth: scale(1),
        borderColor: "#fff",
    },
    customMarkerText: {
        color: "#fff",
        fontWeight: "bold",
    },
    markerIconContainer: {
        width: scale(50),
        height: scale(50),
        justifyContent: 'center',
        alignItems: 'center',
        position: 'relative',
    },
    markerIcon: {
        width: '100%',
        height: '100%',
        resizeMode: 'contain',
    },
    badgeContainer: {
        position: 'absolute',
        right: scale(-10),
        top: scale(-10),
        backgroundColor: 'red',
        borderRadius: scale(10),
        width: scale(20),
        height: scale(20),
        justifyContent: 'center',
        alignItems: 'center',
    },
    badgeText: {
        color: 'white',
        fontSize: scale(12),
    },
});
