import { StyleSheet, Dimensions } from 'react-native';

const { width: screenWidth } = Dimensions.get('window');
const scale = (size) => (screenWidth / 428) * size;

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#F8F8F8',
    padding: scale(20),
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    marginBottom: scale(20),
    position: 'relative',
    paddingBottom: scale(20),
  },
  backButton: {
    padding: scale(10),
    position: 'absolute',
    left: 0,
  },
  headerTitle: {
    fontSize: scale(24),
    fontWeight: 'bold',
    color: '#444',
    position: 'absolute',
    left: 0,
    right: 0,
    textAlign: 'center',
  },
  input: {
    backgroundColor: '#FFF',
    borderWidth: 1,
    borderColor: '#DDD',
    borderRadius: scale(8),
    paddingVertical: scale(14),
    paddingHorizontal: scale(18),
    marginBottom: scale(15),
    fontSize: scale(16),
    width: '100%',
    color: '#555',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: scale(2) },
    shadowOpacity: 0.1,
    shadowRadius: scale(2),
    elevation: scale(2),
  },
  datePicker: {
    marginBottom: scale(20),
  },
  button: {
    backgroundColor: '#FF6347',
    borderRadius: scale(8),
    paddingVertical: scale(14),
    paddingHorizontal: scale(18),
    width: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: scale(20),
    shadowColor: '#FF6347',
    shadowOffset: { width: 0, height: scale(2) },
    shadowOpacity: 0.2,
    shadowRadius: scale(2),
    elevation: scale(3),
  },
  buttonText: {
    color: '#FFF',
    fontSize: scale(18),
    fontWeight: 'bold',
  },
  label: {
    fontSize: scale(18),
    fontWeight: 'bold',
    marginBottom: scale(5),
    color: '#555',
  },
  optionContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: scale(20),
  },
  optionText: {
    fontSize: scale(18),
    color: '#FF6347',
    marginLeft: scale(10),
  },
  centeredView: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(0, 0, 0, 0.4)',
  },
  modalView: {
    backgroundColor: '#FFF',
    borderRadius: scale(20),
    padding: scale(35),
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: scale(2) },
    shadowOpacity: 0.25,
    shadowRadius: scale(3.84),
    elevation: scale(5),
    width: '80%',
    maxWidth: 400, 
  },
  formSubmitButton: {
    backgroundColor: '#4682B4',
    borderRadius: scale(5),
    paddingVertical: scale(10),
    width: '100%',
    alignItems: 'center',
    marginTop: scale(10),
  },
  formSubmitButtonText: {
    color: '#FFF',
    fontSize: scale(18),
    fontWeight: 'bold',
  },
});

export default styles;
